-- ================================================================
-- SnowDDL GitHub Integration - Stage Infrastructure Setup
-- ================================================================
-- Purpose: Create Snowflake infrastructure for GitHub PR automation
-- Author: SnowTower Team
-- Date: 2025-01-14
-- ================================================================

USE ROLE SYSADMIN;
USE DATABASE SNOWDDL_CONFIG;
USE SCHEMA PUBLIC;

-- ================================================================
-- 1. Create Stage for YAML Configuration Files
-- ================================================================

CREATE OR REPLACE STAGE SNOWDDL_CONFIG_STAGE
  COMMENT = 'Stage for storing SnowDDL YAML configuration files pending GitHub PR creation'
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  FILE_FORMAT = (
    TYPE = 'CSV'
    FIELD_DELIMITER = NONE
    RECORD_DELIMITER = NONE
    SKIP_HEADER = 0
    FIELD_OPTIONALLY_ENCLOSED_BY = NONE
    ESCAPE_CHARACTER = NONE
    NULL_IF = ()
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    VALIDATE_UTF8 = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    SKIP_BLANK_LINES = FALSE
    TRIM_SPACE = FALSE
  );

-- Grant necessary permissions
GRANT READ, WRITE ON STAGE SNOWDDL_CONFIG_STAGE TO ROLE SNOWDDL_CONFIG_MANAGER;
GRANT USAGE ON STAGE SNOWDDL_CONFIG_STAGE TO ROLE SNOWDDL_CONFIG_READER;

-- ================================================================
-- 2. Create Request Tracking Table
-- ================================================================

CREATE OR REPLACE TABLE SNOWDDL_CONFIG_REQUESTS (
    REQUEST_ID STRING PRIMARY KEY DEFAULT UUID_STRING(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY STRING NOT NULL,
    REQUEST_TYPE STRING NOT NULL,  -- 'CREATE_PR', 'UPDATE_PR', 'DELETE_BRANCH'
    STATUS STRING NOT NULL DEFAULT 'PENDING',  -- 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'

    -- Configuration Details
    BRANCH_NAME STRING NOT NULL,
    PR_TITLE STRING NOT NULL,
    PR_DESCRIPTION STRING,
    TARGET_BRANCH STRING DEFAULT 'main',

    -- File Information
    STAGE_PATH STRING NOT NULL,  -- Path to file in stage
    FILE_NAME STRING NOT NULL,
    FILE_CONTENT VARIANT,  -- Store the YAML content as JSON

    -- GitHub Integration
    GITHUB_BRANCH_URL STRING,
    GITHUB_PR_URL STRING,
    GITHUB_PR_NUMBER INTEGER,

    -- Processing Information
    PROCESSED_AT TIMESTAMP_NTZ,
    PROCESSOR_ID STRING,  -- ID of the process/lambda that handled this
    ERROR_MESSAGE STRING,
    RETRY_COUNT INTEGER DEFAULT 0,
    MAX_RETRIES INTEGER DEFAULT 3,

    -- Metadata
    TAGS VARIANT,  -- Additional metadata as JSON
    PRIORITY INTEGER DEFAULT 5,  -- 1-10, higher is more urgent

    CONSTRAINT valid_status CHECK (STATUS IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    CONSTRAINT valid_request_type CHECK (REQUEST_TYPE IN ('CREATE_PR', 'UPDATE_PR', 'DELETE_BRANCH')),
    CONSTRAINT valid_priority CHECK (PRIORITY BETWEEN 1 AND 10)
);

-- Add indexes for common queries
CREATE INDEX IF NOT EXISTS idx_config_requests_status ON SNOWDDL_CONFIG_REQUESTS(STATUS);
CREATE INDEX IF NOT EXISTS idx_config_requests_created_at ON SNOWDDL_CONFIG_REQUESTS(CREATED_AT);
CREATE INDEX IF NOT EXISTS idx_config_requests_branch ON SNOWDDL_CONFIG_REQUESTS(BRANCH_NAME);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SNOWDDL_CONFIG_REQUESTS TO ROLE SNOWDDL_CONFIG_MANAGER;
GRANT SELECT ON TABLE SNOWDDL_CONFIG_REQUESTS TO ROLE SNOWDDL_CONFIG_READER;

-- ================================================================
-- 3. Create Processing Log Table
-- ================================================================

CREATE OR REPLACE TABLE SNOWDDL_CONFIG_PROCESSING_LOG (
    LOG_ID STRING PRIMARY KEY DEFAULT UUID_STRING(),
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REQUEST_ID STRING,
    LEVEL STRING NOT NULL,  -- 'INFO', 'WARN', 'ERROR', 'DEBUG'
    MESSAGE STRING NOT NULL,
    DETAILS VARIANT,  -- Additional structured data
    PROCESSOR_ID STRING,

    CONSTRAINT fk_processing_log_request
        FOREIGN KEY (REQUEST_ID) REFERENCES SNOWDDL_CONFIG_REQUESTS(REQUEST_ID),
    CONSTRAINT valid_log_level CHECK (LEVEL IN ('DEBUG', 'INFO', 'WARN', 'ERROR'))
);

-- Grant permissions
GRANT SELECT, INSERT ON TABLE SNOWDDL_CONFIG_PROCESSING_LOG TO ROLE SNOWDDL_CONFIG_MANAGER;
GRANT SELECT ON TABLE SNOWDDL_CONFIG_PROCESSING_LOG TO ROLE SNOWDDL_CONFIG_READER;

-- ================================================================
-- 4. Create Views for Monitoring
-- ================================================================

CREATE OR REPLACE VIEW V_PENDING_REQUESTS AS
SELECT
    REQUEST_ID,
    CREATED_AT,
    CREATED_BY,
    REQUEST_TYPE,
    BRANCH_NAME,
    PR_TITLE,
    STAGE_PATH,
    FILE_NAME,
    PRIORITY,
    RETRY_COUNT,
    DATEDIFF('minute', CREATED_AT, CURRENT_TIMESTAMP()) AS AGE_MINUTES
FROM SNOWDDL_CONFIG_REQUESTS
WHERE STATUS = 'PENDING'
  AND RETRY_COUNT < MAX_RETRIES
ORDER BY PRIORITY DESC, CREATED_AT ASC;

CREATE OR REPLACE VIEW V_FAILED_REQUESTS AS
SELECT
    REQUEST_ID,
    CREATED_AT,
    CREATED_BY,
    REQUEST_TYPE,
    BRANCH_NAME,
    STATUS,
    ERROR_MESSAGE,
    RETRY_COUNT,
    MAX_RETRIES,
    PROCESSED_AT
FROM SNOWDDL_CONFIG_REQUESTS
WHERE STATUS = 'FAILED' OR RETRY_COUNT >= MAX_RETRIES
ORDER BY CREATED_AT DESC;

CREATE OR REPLACE VIEW V_REQUEST_SUMMARY AS
SELECT
    DATE_TRUNC('hour', CREATED_AT) AS HOUR,
    STATUS,
    REQUEST_TYPE,
    COUNT(*) AS REQUEST_COUNT,
    AVG(DATEDIFF('minute', CREATED_AT, COALESCE(PROCESSED_AT, CURRENT_TIMESTAMP()))) AS AVG_PROCESSING_TIME_MINUTES
FROM SNOWDDL_CONFIG_REQUESTS
WHERE CREATED_AT >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY DATE_TRUNC('hour', CREATED_AT), STATUS, REQUEST_TYPE
ORDER BY HOUR DESC;

-- Grant view permissions
GRANT SELECT ON VIEW V_PENDING_REQUESTS TO ROLE SNOWDDL_CONFIG_READER;
GRANT SELECT ON VIEW V_FAILED_REQUESTS TO ROLE SNOWDDL_CONFIG_READER;
GRANT SELECT ON VIEW V_REQUEST_SUMMARY TO ROLE SNOWDDL_CONFIG_READER;

-- ================================================================
-- 5. Create Configuration Table for GitHub Settings
-- ================================================================

CREATE OR REPLACE TABLE SNOWDDL_GITHUB_CONFIG (
    CONFIG_KEY STRING PRIMARY KEY,
    CONFIG_VALUE STRING NOT NULL,
    DESCRIPTION STRING,
    ENCRYPTED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY STRING
);

-- Insert default configuration
INSERT INTO SNOWDDL_GITHUB_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION, ENCRYPTED) VALUES
('GITHUB_REPO_OWNER', 'your-org', 'GitHub repository owner/organization name', FALSE),
('GITHUB_REPO_NAME', 'snowddl-config', 'GitHub repository name', FALSE),
('GITHUB_BASE_BRANCH', 'main', 'Default base branch for PRs', FALSE),
('GITHUB_API_URL', 'https://api.github.com', 'GitHub API base URL', FALSE),
('PR_AUTO_MERGE', 'false', 'Whether to auto-merge PRs after creation', FALSE),
('PR_REVIEWER_TEAMS', '[]', 'JSON array of GitHub teams to request review from', FALSE),
('PROCESSOR_INTERVAL_MINUTES', '5', 'How often the processor should run (minutes)', FALSE),
('MAX_FILES_PER_PR', '10', 'Maximum number of files to include in a single PR', FALSE);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE ON TABLE SNOWDDL_GITHUB_CONFIG TO ROLE SNOWDDL_CONFIG_MANAGER;
GRANT SELECT ON TABLE SNOWDDL_GITHUB_CONFIG TO ROLE SNOWDDL_CONFIG_READER;

-- ================================================================
-- Verification Queries
-- ================================================================

-- Check that all objects were created successfully
SELECT 'STAGE' AS OBJECT_TYPE, 'SNOWDDL_CONFIG_STAGE' AS OBJECT_NAME,
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS STATUS
FROM INFORMATION_SCHEMA.STAGES WHERE STAGE_NAME = 'SNOWDDL_CONFIG_STAGE'
UNION ALL
SELECT 'TABLE' AS OBJECT_TYPE, 'SNOWDDL_CONFIG_REQUESTS' AS OBJECT_NAME,
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS STATUS
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SNOWDDL_CONFIG_REQUESTS'
UNION ALL
SELECT 'TABLE' AS OBJECT_TYPE, 'SNOWDDL_CONFIG_PROCESSING_LOG' AS OBJECT_NAME,
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS STATUS
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SNOWDDL_CONFIG_PROCESSING_LOG'
UNION ALL
SELECT 'TABLE' AS OBJECT_TYPE, 'SNOWDDL_GITHUB_CONFIG' AS OBJECT_NAME,
       CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END AS STATUS
FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SNOWDDL_GITHUB_CONFIG';

-- Display current configuration
SELECT * FROM SNOWDDL_GITHUB_CONFIG ORDER BY CONFIG_KEY;
