# Generated by SnowTower - DO NOT EDIT MANUALLY
# Source: snowddl/ YAML configurations

# Database resources

import {
  to = snowflake_database.dev_example
  id = "DEV_EXAMPLE"
}

resource "snowflake_database" "dev_example" {
  name    = "DEV_EXAMPLE"
  comment = "Sandbox database DEV_EXAMPLE"
}

import {
  to = snowflake_database.lightdash
  id = "LIGHTDASH"
}

resource "snowflake_database" "lightdash" {
  name    = "LIGHTDASH"
  comment = "LightDash BI platform database for analytics transformations and dashboard content"
}

import {
  to = snowflake_database.omni
  id = "OMNI"
}

resource "snowflake_database" "omni" {
  name    = "OMNI"
  comment = "Omni BI platform database for analytics transformations and custom reporting"
}
