# Generated by SnowTower - DO NOT EDIT MANUALLY
# Source: snowddl/ YAML configurations

# Grant resources

resource "snowflake_grant_account_role" "admin_role_b_role_inherits_streamlit_viewer_t_role" {
  role_name        = "STREAMLIT_VIEWER__T_ROLE"
  parent_role_name = "ADMIN_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "admin_role_b_role_inherits_dlt_loader_role_t_role" {
  role_name        = "DLT_LOADER_ROLE__T_ROLE"
  parent_role_name = "ADMIN_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "admin_role_b_role_inherits_snowtower_users_t_role" {
  role_name        = "SNOWTOWER_USERS__T_ROLE"
  parent_role_name = "ADMIN_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "admin_role_b_role_inherits_stripe_t_role" {
  role_name        = "STRIPE__T_ROLE"
  parent_role_name = "ADMIN_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "admin_role_b_role_inherits_company_users_t_role" {
  role_name        = "COMPANY_USERS__T_ROLE"
  parent_role_name = "ADMIN_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "admin_role_b_role_wh_admin" {
  account_role_name = "ADMIN_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ADMIN"
  }
}

resource "snowflake_grant_privileges_to_account_role" "admin_role_b_role_wh_main_warehouse" {
  account_role_name = "ADMIN_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "MAIN_WAREHOUSE"
  }
}

resource "snowflake_grant_account_role" "ai_ml_role_b_role_inherits_fabi_ai_t_role" {
  role_name        = "FABI_AI__T_ROLE"
  parent_role_name = "AI_ML_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "ai_ml_role_b_role_inherits_copilot_access_role_t_role" {
  role_name        = "COPILOT_ACCESS_ROLE__T_ROLE"
  parent_role_name = "AI_ML_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "ai_ml_role_b_role_wh_fabi_ai_warehouse" {
  account_role_name = "AI_ML_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "FABI_AI_WAREHOUSE"
  }
}

resource "snowflake_grant_account_role" "bi_developer_role_b_role_inherits_streamlit_viewer_t_role" {
  role_name        = "STREAMLIT_VIEWER__T_ROLE"
  parent_role_name = "BI_DEVELOPER_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "bi_developer_role_b_role_inherits_dbt_stripe_role_t_role" {
  role_name        = "DBT_STRIPE_ROLE__T_ROLE"
  parent_role_name = "BI_DEVELOPER_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "bi_developer_role_b_role_inherits_bi_writer_tech_role_t_role" {
  role_name        = "BI_WRITER_TECH_ROLE__T_ROLE"
  parent_role_name = "BI_DEVELOPER_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "bi_developer_role_b_role_inherits_sigma_role_t_role" {
  role_name        = "SIGMA_ROLE__T_ROLE"
  parent_role_name = "BI_DEVELOPER_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "bi_developer_role_b_role_wh_transforming" {
  account_role_name = "BI_DEVELOPER_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING"
  }
}

resource "snowflake_grant_privileges_to_account_role" "bi_developer_role_b_role_wh_analytics_tool" {
  account_role_name = "BI_DEVELOPER_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "bi_developer_role_b_role_wh_main_warehouse" {
  account_role_name = "BI_DEVELOPER_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "MAIN_WAREHOUSE"
  }
}

resource "snowflake_grant_account_role" "company_users_b_role_inherits_streamlit_viewer_t_role" {
  role_name        = "STREAMLIT_VIEWER__T_ROLE"
  parent_role_name = "COMPANY_USERS__B_ROLE"
}

resource "snowflake_grant_account_role" "company_users_b_role_inherits_dlt_loader_role_t_role" {
  role_name        = "DLT_LOADER_ROLE__T_ROLE"
  parent_role_name = "COMPANY_USERS__B_ROLE"
}

resource "snowflake_grant_account_role" "company_users_b_role_inherits_stripe_t_role" {
  role_name        = "STRIPE__T_ROLE"
  parent_role_name = "COMPANY_USERS__B_ROLE"
}

resource "snowflake_grant_account_role" "company_users_b_role_inherits_company_users_t_role" {
  role_name        = "COMPANY_USERS__T_ROLE"
  parent_role_name = "COMPANY_USERS__B_ROLE"
}

resource "snowflake_grant_account_role" "company_users_b_role_inherits_dbt_stripe_role_t_role" {
  role_name        = "DBT_STRIPE_ROLE__T_ROLE"
  parent_role_name = "COMPANY_USERS__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "company_users_b_role_wh_main_warehouse" {
  account_role_name = "COMPANY_USERS__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "MAIN_WAREHOUSE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_b_role_wh_dlt" {
  account_role_name = "COMPANY_USERS__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "DLT"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_b_role_wh_stripe" {
  account_role_name = "COMPANY_USERS__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_b_role_wh_transforming" {
  account_role_name = "COMPANY_USERS__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_b_role_wh_dev_wh" {
  account_role_name = "COMPANY_USERS__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "DEV_WH"
  }
}

resource "snowflake_grant_account_role" "data_integration_role_b_role_inherits_estuary_t_role" {
  role_name        = "ESTUARY__T_ROLE"
  parent_role_name = "DATA_INTEGRATION_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "data_integration_role_b_role_inherits_fivetran_t_role" {
  role_name        = "FIVETRAN__T_ROLE"
  parent_role_name = "DATA_INTEGRATION_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "data_integration_role_b_role_inherits_fivetran_role_t_role" {
  role_name        = "FIVETRAN_ROLE__T_ROLE"
  parent_role_name = "DATA_INTEGRATION_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "data_integration_role_b_role_inherits_matillion_role_t_role" {
  role_name        = "MATILLION_ROLE__T_ROLE"
  parent_role_name = "DATA_INTEGRATION_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "data_integration_role_b_role_inherits_dlt_loader_role_t_role" {
  role_name        = "DLT_LOADER_ROLE__T_ROLE"
  parent_role_name = "DATA_INTEGRATION_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "data_integration_role_b_role_wh_estuary" {
  account_role_name = "DATA_INTEGRATION_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ESTUARY"
  }
}

resource "snowflake_grant_privileges_to_account_role" "data_integration_role_b_role_wh_fivetran" {
  account_role_name = "DATA_INTEGRATION_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "FIVETRAN"
  }
}

resource "snowflake_grant_privileges_to_account_role" "data_integration_role_b_role_wh_transforming" {
  account_role_name = "DATA_INTEGRATION_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING"
  }
}

resource "snowflake_grant_privileges_to_account_role" "data_integration_role_b_role_wh_stripe" {
  account_role_name = "DATA_INTEGRATION_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "STRIPE"
  }
}

resource "snowflake_grant_account_role" "dbt_analytics_role_b_role_inherits_dbt_stripe_role_t_role" {
  role_name        = "DBT_STRIPE_ROLE__T_ROLE"
  parent_role_name = "DBT_ANALYTICS_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "dbt_analytics_role_b_role_inherits_dbt_training_t_role" {
  role_name        = "DBT_TRAINING__T_ROLE"
  parent_role_name = "DBT_ANALYTICS_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "dbt_analytics_role_b_role_wh_main_warehouse" {
  account_role_name = "DBT_ANALYTICS_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "MAIN_WAREHOUSE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dbt_analytics_role_b_role_wh_transforming" {
  account_role_name = "DBT_ANALYTICS_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING"
  }
}

resource "snowflake_grant_account_role" "dbt_analytics_role_b_role_owner_proj_stripe_proj_stripe" {
  role_name        = "PROJ_STRIPE__PROJ_STRIPE__OWNER__S_ROLE"
  parent_role_name = "DBT_ANALYTICS_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "dlt_stripe_role_b_role_inherits_dlt_stripe_tech_role_t_role" {
  role_name        = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  parent_role_name = "DLT_STRIPE_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_role_b_role_wh_dlt" {
  account_role_name = "DLT_STRIPE_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "DLT"
  }
}

resource "snowflake_grant_account_role" "dlt_stripe_role_b_role_owner_source_stripe_stripe_why" {
  role_name        = "SOURCE_STRIPE__STRIPE_WHY__OWNER__S_ROLE"
  parent_role_name = "DLT_STRIPE_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "infrastructure_automation_role_b_role_inherits_omni_infrastructure_automation_t_role" {
  role_name        = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
  parent_role_name = "INFRASTRUCTURE_AUTOMATION_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "infrastructure_automation_role_b_role_inherits_tobiko_cloud_t_role" {
  role_name        = "TOBIKO_CLOUD__T_ROLE"
  parent_role_name = "INFRASTRUCTURE_AUTOMATION_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "infrastructure_automation_role_b_role_wh_analytics_tool" {
  account_role_name = "INFRASTRUCTURE_AUTOMATION_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "infrastructure_automation_role_b_role_wh_admin" {
  account_role_name = "INFRASTRUCTURE_AUTOMATION_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ADMIN"
  }
}

resource "snowflake_grant_account_role" "lightdash_business_role_b_role_inherits_lightdash_tech_role_t_role" {
  role_name        = "LIGHTDASH_TECH_ROLE__T_ROLE"
  parent_role_name = "LIGHTDASH_BUSINESS_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_business_role_b_role_wh_bi_tool" {
  account_role_name = "LIGHTDASH_BUSINESS_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "BI_TOOL"
  }
}

resource "snowflake_grant_account_role" "omni_business_role_b_role_inherits_omni_tech_role_t_role" {
  role_name        = "OMNI_TECH_ROLE__T_ROLE"
  parent_role_name = "OMNI_BUSINESS_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "omni_business_role_b_role_wh_analytics_tool" {
  account_role_name = "OMNI_BUSINESS_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_account_role" "recce_business_role_b_role_inherits_recce_tech_role_t_role" {
  role_name        = "RECCE_TECH_ROLE__T_ROLE"
  parent_role_name = "RECCE_BUSINESS_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "recce_business_role_b_role_wh_recce" {
  account_role_name = "RECCE_BUSINESS_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "RECCE"
  }
}

resource "snowflake_grant_account_role" "service_accounts_role_b_role_inherits_tobiko_cloud_t_role" {
  role_name        = "TOBIKO_CLOUD__T_ROLE"
  parent_role_name = "SERVICE_ACCOUNTS_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "service_accounts_role_b_role_wh_admin" {
  account_role_name = "SERVICE_ACCOUNTS_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ADMIN"
  }
}

resource "snowflake_grant_account_role" "streamlit_apps_role_b_role_inherits_streamlit_role_t_role" {
  role_name        = "STREAMLIT_ROLE__T_ROLE"
  parent_role_name = "STREAMLIT_APPS_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "streamlit_apps_role_b_role_inherits_streamlit_towerapp_role_t_role" {
  role_name        = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  parent_role_name = "STREAMLIT_APPS_ROLE__B_ROLE"
}

resource "snowflake_grant_account_role" "streamlit_apps_role_b_role_inherits_streamlit_viewer_t_role" {
  role_name        = "STREAMLIT_VIEWER__T_ROLE"
  parent_role_name = "STREAMLIT_APPS_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_apps_role_b_role_wh_streamlit_viewer_wh" {
  account_role_name = "STREAMLIT_APPS_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "STREAMLIT_VIEWER_WH"
  }
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_apps_role_b_role_wh_main_warehouse" {
  account_role_name = "STREAMLIT_APPS_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "MAIN_WAREHOUSE"
  }
}

resource "snowflake_grant_account_role" "training_role_b_role_inherits_dbt_training_t_role" {
  role_name        = "DBT_TRAINING__T_ROLE"
  parent_role_name = "TRAINING_ROLE__B_ROLE"
}

resource "snowflake_grant_privileges_to_account_role" "training_role_b_role_wh_transforming_user" {
  account_role_name = "TRAINING_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING_USER"
  }
}

resource "snowflake_grant_privileges_to_account_role" "training_role_b_role_wh_transforming" {
  account_role_name = "TRAINING_ROLE__B_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING"
  }
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_grant_database_proj_stripe_usage" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_grant_database_source_stripe_usage" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "SOURCE_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_grant_database_analytics_tool_usage_create_schema" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_grant_schema_source_stripe_stripe_why_usage" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_grant_warehouse_transforming_usage" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING"
  }
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_grant_warehouse_analytics_tool_usage" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_future_table_proj_stripe_select" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_future_table_source_stripe_select" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_future_table_analytics_tool_select_insert_update_delete_truncate" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "bi_writer_tech_role_t_role_future_view_analytics_tool_select" {
  account_role_name = "BI_WRITER_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_database_dev_alice_usage_create_schema" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "DEV_ALICE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_database_dev_carol_usage_create_schema" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "DEV_CAROL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_database_dev_dave_usage_create_schema" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "DEV_DAVE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_database_dev_eve_usage_create_schema" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "DEV_EVE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_database_dev_grace_usage_create_schema" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "DEV_GRACE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_database_dev_bob_usage_create_schema" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "DEV_BOB"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_database_dev_frank_usage_create_schema" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "DEV_FRANK"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_schema_source_stripe_stripe_why_usage" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_schema_dev_alice_stripe_why_usage_modify_monitor_create_table_create_view_create_function_create_procedure_create_file_format_create_stage_create_sequence" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "MODIFY", "MONITOR", "CREATE TABLE", "CREATE VIEW", "CREATE FUNCTION", "CREATE PROCEDURE", "CREATE FILE FORMAT", "CREATE STAGE", "CREATE SEQUENCE"]
  on_schema {
    schema_name       = "\"DEV_ALICE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_grant_warehouse_main_warehouse_usage" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "MAIN_WAREHOUSE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_stage_dev_alice_usage_read_write" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "READ", "WRITE"]
  on_schema_object {
    object_type_plural = "STAGES"
    in_database       = "DEV_ALICE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_stage_dev_carol_usage_read_write" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "READ", "WRITE"]
  on_schema_object {
    object_type_plural = "STAGES"
    in_database       = "DEV_CAROL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_stage_dev_dave_usage_read_write" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "READ", "WRITE"]
  on_schema_object {
    object_type_plural = "STAGES"
    in_database       = "DEV_DAVE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_stage_dev_eve_usage_read_write" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "READ", "WRITE"]
  on_schema_object {
    object_type_plural = "STAGES"
    in_database       = "DEV_EVE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_stage_dev_grace_usage_read_write" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "READ", "WRITE"]
  on_schema_object {
    object_type_plural = "STAGES"
    in_database       = "DEV_GRACE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_stage_dev_bob_usage_read_write" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "READ", "WRITE"]
  on_schema_object {
    object_type_plural = "STAGES"
    in_database       = "DEV_BOB"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_stage_dev_frank_usage_read_write" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["USAGE", "READ", "WRITE"]
  on_schema_object {
    object_type_plural = "STAGES"
    in_database       = "DEV_FRANK"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_table_dev_alice_select_insert_update_delete_truncate" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "DEV_ALICE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_table_dev_carol_select_insert_update_delete_truncate" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "DEV_CAROL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_table_dev_dave_select_insert_update_delete_truncate" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "DEV_DAVE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_table_dev_eve_select_insert_update_delete_truncate" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "DEV_EVE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_table_dev_grace_select_insert_update_delete_truncate" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "DEV_GRACE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_table_dev_bob_select_insert_update_delete_truncate" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "DEV_BOB"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "company_users_t_role_future_table_dev_frank_select_insert_update_delete_truncate" {
  account_role_name = "COMPANY_USERS__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "DEV_FRANK"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "copilot_access_role_t_role_grant_warehouse_main_warehouse_usage" {
  account_role_name = "COPILOT_ACCESS_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "MAIN_WAREHOUSE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_grant_database_source_stripe_usage_create_schema" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "SOURCE_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_grant_database_proj_stripe_usage_create_schema" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_grant_database_analytics_tool_usage_create_schema" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_grant_schema_source_stripe_stripe_why_usage" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_grant_schema_proj_stripe_proj_stripe_usage_modify_monitor_create_table_create_view_create_function_create_procedure_create_file_format_create_stage_create_sequence" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["USAGE", "MODIFY", "MONITOR", "CREATE TABLE", "CREATE VIEW", "CREATE FUNCTION", "CREATE PROCEDURE", "CREATE FILE FORMAT", "CREATE STAGE", "CREATE SEQUENCE"]
  on_schema {
    schema_name       = "\"PROJ_STRIPE.PROJ_STRIPE\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_grant_warehouse_transforming_usage" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_future_table_source_stripe_select" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_future_table_proj_stripe_select_insert_update_delete_truncate" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_future_table_analytics_tool_select_insert_update_delete_truncate" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_future_view_source_stripe_select" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_future_view_proj_stripe_select" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dbt_stripe_role_t_role_future_view_analytics_tool_select" {
  account_role_name = "DBT_STRIPE_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dbt_training_t_role_grant_warehouse_transforming_usage" {
  account_role_name = "DBT_TRAINING__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dlt_loader_role_t_role_grant_database_source_stripe_usage_create_schema" {
  account_role_name = "DLT_LOADER_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "SOURCE_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dlt_loader_role_t_role_grant_schema_source_stripe_stripe_why_usage" {
  account_role_name = "DLT_LOADER_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "dlt_loader_role_t_role_future_table_source_stripe_select_insert_update_delete_truncate" {
  account_role_name = "DLT_LOADER_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_loader_role_t_role_future_view_source_stripe_select" {
  account_role_name = "DLT_LOADER_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_grant_database_source_stripe_usage_create_schema_monitor_modify" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA", "MONITOR", "MODIFY"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "SOURCE_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_grant_database_proj_stripe_usage_create_schema_monitor_modify" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA", "MONITOR", "MODIFY"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_grant_schema_source_stripe_stripe_why_usage_modify_monitor_create_table_create_view_create_file_format_create_stage_create_sequence" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE", "MODIFY", "MONITOR", "CREATE TABLE", "CREATE VIEW", "CREATE FILE FORMAT", "CREATE STAGE", "CREATE SEQUENCE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_grant_warehouse_dlt_usage_monitor_operate" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE", "MONITOR", "OPERATE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "DLT"
  }
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_file_format_source_stripe_usage" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema_object {
    object_type_plural = "FILE_FORMATS"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_file_format_proj_stripe_usage" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema_object {
    object_type_plural = "FILE_FORMATS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_sequence_source_stripe_usage" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema_object {
    object_type_plural = "SEQUENCES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_sequence_proj_stripe_usage" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema_object {
    object_type_plural = "SEQUENCES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_stage_source_stripe_usage_read_write" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE", "READ", "WRITE"]
  on_schema_object {
    object_type_plural = "STAGES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_stage_proj_stripe_usage_read_write" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE", "READ", "WRITE"]
  on_schema_object {
    object_type_plural = "STAGES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_table_source_stripe_select_insert_update_delete_truncate_references" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_table_proj_stripe_select_insert_update_delete_truncate_references" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE", "REFERENCES"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_view_source_stripe_select" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "dlt_stripe_tech_role_t_role_future_view_proj_stripe_select" {
  account_role_name = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "estuary_t_role_grant_warehouse_estuary_usage" {
  account_role_name = "ESTUARY__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ESTUARY"
  }
}

resource "snowflake_grant_privileges_to_account_role" "fabi_ai_t_role_grant_warehouse_fabi_ai_warehouse_usage" {
  account_role_name = "FABI_AI__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "FABI_AI_WAREHOUSE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "fivetran_t_role_grant_warehouse_fivetran_usage" {
  account_role_name = "FIVETRAN__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "FIVETRAN"
  }
}

resource "snowflake_grant_privileges_to_account_role" "fivetran_role_t_role_grant_database_source_stripe_usage_create_schema" {
  account_role_name = "FIVETRAN_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "SOURCE_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "fivetran_role_t_role_grant_schema_source_stripe_stripe_why_usage" {
  account_role_name = "FIVETRAN_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "fivetran_role_t_role_grant_warehouse_fivetran_usage" {
  account_role_name = "FIVETRAN_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "FIVETRAN"
  }
}

resource "snowflake_grant_privileges_to_account_role" "fivetran_role_t_role_future_table_source_stripe_select_insert_update_delete_truncate" {
  account_role_name = "FIVETRAN_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_grant_database_proj_stripe_usage" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_grant_database_source_stripe_usage" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "SOURCE_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_grant_database_bi_tool_usage_create_schema" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "BI_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_grant_schema_source_stripe_stripe_why_usage" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_grant_warehouse_bi_tool_usage" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "BI_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_future_table_proj_stripe_select" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_future_table_source_stripe_select" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_future_table_bi_tool_select_insert_update_delete_truncate" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "BI_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_future_view_proj_stripe_select" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_future_view_source_stripe_select" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "lightdash_tech_role_t_role_future_view_bi_tool_select" {
  account_role_name = "LIGHTDASH_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "BI_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "matillion_role_t_role_grant_database_source_stripe_usage_create_schema" {
  account_role_name = "MATILLION_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "SOURCE_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "matillion_role_t_role_grant_database_proj_stripe_usage_create_schema" {
  account_role_name = "MATILLION_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "matillion_role_t_role_grant_schema_source_stripe_stripe_why_usage" {
  account_role_name = "MATILLION_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "matillion_role_t_role_grant_warehouse_transforming_usage" {
  account_role_name = "MATILLION_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "TRANSFORMING"
  }
}

resource "snowflake_grant_privileges_to_account_role" "matillion_role_t_role_future_table_source_stripe_select_insert_update_delete_truncate" {
  account_role_name = "MATILLION_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "matillion_role_t_role_future_table_proj_stripe_select_insert_update_delete_truncate" {
  account_role_name = "MATILLION_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "omni_infrastructure_automation_t_role_grant_database_analytics_tool_usage_create_schema_monitor" {
  account_role_name = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA", "MONITOR"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "omni_infrastructure_automation_t_role_grant_database_proj_stripe_usage_create_schema_monitor" {
  account_role_name = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA", "MONITOR"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "omni_infrastructure_automation_t_role_grant_warehouse_analytics_tool_usage_monitor_operate" {
  account_role_name = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
  privileges        = ["USAGE", "MONITOR", "OPERATE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "omni_infrastructure_automation_t_role_grant_warehouse_admin_usage_monitor_operate" {
  account_role_name = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
  privileges        = ["USAGE", "MONITOR", "OPERATE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ADMIN"
  }
}

resource "snowflake_grant_privileges_to_account_role" "omni_infrastructure_automation_t_role_future_table_analytics_tool_select_insert_update_delete_truncate" {
  account_role_name = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "omni_infrastructure_automation_t_role_future_view_analytics_tool_select" {
  account_role_name = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "omni_infrastructure_automation_t_role_future_view_proj_stripe_select" {
  account_role_name = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "omni_tech_role_t_role_grant_database_proj_stripe_usage" {
  account_role_name = "OMNI_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "omni_tech_role_t_role_grant_database_analytics_tool_usage_create_schema" {
  account_role_name = "OMNI_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "omni_tech_role_t_role_grant_warehouse_analytics_tool_usage" {
  account_role_name = "OMNI_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "omni_tech_role_t_role_future_table_proj_stripe_select" {
  account_role_name = "OMNI_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "omni_tech_role_t_role_future_table_analytics_tool_select_insert_update_delete_truncate" {
  account_role_name = "OMNI_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "omni_tech_role_t_role_future_view_analytics_tool_select" {
  account_role_name = "OMNI_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "recce_tech_role_t_role_grant_database_proj_stripe_usage" {
  account_role_name = "RECCE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "recce_tech_role_t_role_grant_warehouse_recce_usage" {
  account_role_name = "RECCE_TECH_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "RECCE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "recce_tech_role_t_role_future_table_proj_stripe_select" {
  account_role_name = "RECCE_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "recce_tech_role_t_role_future_view_proj_stripe_select" {
  account_role_name = "RECCE_TECH_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "sigma_role_t_role_grant_database_proj_stripe_usage" {
  account_role_name = "SIGMA_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "sigma_role_t_role_grant_database_analytics_tool_usage" {
  account_role_name = "SIGMA_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "sigma_role_t_role_grant_warehouse_analytics_tool_usage" {
  account_role_name = "SIGMA_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ANALYTICS_TOOL"
  }
}

resource "snowflake_grant_privileges_to_account_role" "sigma_role_t_role_future_table_proj_stripe_select" {
  account_role_name = "SIGMA_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "sigma_role_t_role_future_table_analytics_tool_select" {
  account_role_name = "SIGMA_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "sigma_role_t_role_future_view_proj_stripe_select" {
  account_role_name = "SIGMA_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "sigma_role_t_role_future_view_analytics_tool_select" {
  account_role_name = "SIGMA_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "ANALYTICS_TOOL"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "snowtower_users_t_role_grant_warehouse_main_warehouse_usage" {
  account_role_name = "SNOWTOWER_USERS__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "MAIN_WAREHOUSE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_role_t_role_grant_database_proj_stripe_usage" {
  account_role_name = "STREAMLIT_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_role_t_role_grant_warehouse_streamlit_viewer_wh_usage" {
  account_role_name = "STREAMLIT_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "STREAMLIT_VIEWER_WH"
  }
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_role_t_role_future_table_proj_stripe_select" {
  account_role_name = "STREAMLIT_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_role_t_role_future_view_proj_stripe_select" {
  account_role_name = "STREAMLIT_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_towerapp_role_t_role_grant_database_proj_stripe_usage" {
  account_role_name = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_towerapp_role_t_role_grant_database_source_stripe_usage" {
  account_role_name = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "SOURCE_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_towerapp_role_t_role_grant_schema_source_stripe_stripe_why_usage" {
  account_role_name = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_towerapp_role_t_role_grant_warehouse_streamlit_viewer_wh_usage" {
  account_role_name = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "STREAMLIT_VIEWER_WH"
  }
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_towerapp_role_t_role_grant_warehouse_main_warehouse_usage" {
  account_role_name = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "MAIN_WAREHOUSE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_towerapp_role_t_role_future_table_proj_stripe_select" {
  account_role_name = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_towerapp_role_t_role_future_table_source_stripe_select" {
  account_role_name = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_towerapp_role_t_role_future_view_proj_stripe_select" {
  account_role_name = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_towerapp_role_t_role_future_view_source_stripe_select" {
  account_role_name = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "streamlit_viewer_t_role_grant_warehouse_streamlit_viewer_wh_usage" {
  account_role_name = "STREAMLIT_VIEWER__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "STREAMLIT_VIEWER_WH"
  }
}

resource "snowflake_grant_privileges_to_account_role" "stripe_t_role_grant_database_source_stripe_usage_create_schema" {
  account_role_name = "STRIPE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "SOURCE_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "stripe_t_role_grant_database_proj_stripe_usage_create_schema" {
  account_role_name = "STRIPE__T_ROLE"
  privileges        = ["USAGE", "CREATE SCHEMA"]
  on_account_object {
    object_type       = "DATABASE"
    object_name       = "PROJ_STRIPE"
  }
}

resource "snowflake_grant_privileges_to_account_role" "stripe_t_role_grant_schema_source_stripe_stripe_why_usage" {
  account_role_name = "STRIPE__T_ROLE"
  privileges        = ["USAGE"]
  on_schema {
    schema_name       = "\"SOURCE_STRIPE.STRIPE_WHY\""
  }
}

resource "snowflake_grant_privileges_to_account_role" "stripe_t_role_future_table_source_stripe_select" {
  account_role_name = "STRIPE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "stripe_t_role_future_table_proj_stripe_select" {
  account_role_name = "STRIPE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "TABLES"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "stripe_t_role_future_view_source_stripe_select" {
  account_role_name = "STRIPE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "SOURCE_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "stripe_t_role_future_view_proj_stripe_select" {
  account_role_name = "STRIPE__T_ROLE"
  privileges        = ["SELECT"]
  on_schema_object {
    object_type_plural = "VIEWS"
    in_database       = "PROJ_STRIPE"
  }
  all_privileges    = false
  with_grant_option = false
}

resource "snowflake_grant_privileges_to_account_role" "tobiko_cloud_t_role_grant_warehouse_admin_usage" {
  account_role_name = "TOBIKO_CLOUD__T_ROLE"
  privileges        = ["USAGE"]
  on_account_object {
    object_type       = "WAREHOUSE"
    object_name       = "ADMIN"
  }
}
