# Generated by SnowTower - DO NOT EDIT MANUALLY
# Source: snowddl/ YAML configurations

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 1.0"
    }
  }
}
