# Generated by SnowTower - DO NOT EDIT MANUALLY
# Source: snowddl/ YAML configurations

# Policy resources (network, authentication, password, session)

import {
  to = snowflake_network_policy.analytics_network_policy
  id = "ANALYTICS_NETWORK_POLICY"
}

resource "snowflake_network_policy" "analytics_network_policy" {
  name            = "ANALYTICS_NETWORK_POLICY"
  allowed_ip_list = ["3.211.115.21/32", "34.215.77.3/32", "44.199.154.198/32", "52.205.119.255/32", "52.33.167.28/32", "54.172.168.164/32", "54.213.140.155/32", "54.213.219.131/32"]
  comment         = "Restrict Omni BI platform service account to approved Omni IP addresses"
}

import {
  to = snowflake_network_policy.bi_tool_network_policy
  id = "BI_TOOL_NETWORK_POLICY"
}

resource "snowflake_network_policy" "bi_tool_network_policy" {
  name            = "BI_TOOL_NETWORK_POLICY"
  allowed_ip_list = ["198.51.100.1/32", "198.51.100.2/32", "192.0.2.10/32"]
  comment         = "Restrict LightDash BI platform service account to approved LightDash IP addresses (US and EU regions)"
}

import {
  to = snowflake_network_policy.company_network_policy
  id = "COMPANY_NETWORK_POLICY"
}

resource "snowflake_network_policy" "company_network_policy" {
  name            = "COMPANY_NETWORK_POLICY"
  allowed_ip_list = ["192.0.2.10/32"]
  comment         = "Restrict human user access to approved IP address only"
}

import {
  to = snowflake_authentication_policy.mfa_optional_policy
  id = "MFA_OPTIONAL_POLICY"
}

resource "snowflake_authentication_policy" "mfa_optional_policy" {
  name                       = "MFA_OPTIONAL_POLICY"
  comment                    = "Optional MFA policy for transition period before mandatory enforcement"
  client_types               = ["ALL"]
  mfa_authentication_methods = ["PASSWORD", "SAML"]
  mfa_enrollment             = "OPTIONAL"
}

import {
  to = snowflake_authentication_policy.mfa_required_policy
  id = "MFA_REQUIRED_POLICY"
}

resource "snowflake_authentication_policy" "mfa_required_policy" {
  name                       = "MFA_REQUIRED_POLICY"
  comment                    = "Mandatory MFA policy for human users (TYPE=PERSON) to comply with Snowflake MFA rollout timeline"
  client_types               = ["SNOWFLAKE_UI", "SNOWFLAKE_CLI", "DRIVERS", "SNOWSQL"]
  mfa_authentication_methods = ["PASSWORD"]
  mfa_enrollment             = "REQUIRED"
}

import {
  to = snowflake_authentication_policy.service_account_policy
  id = "SERVICE_ACCOUNT_POLICY"
}

resource "snowflake_authentication_policy" "service_account_policy" {
  name         = "SERVICE_ACCOUNT_POLICY"
  comment      = "Restricted client access policy for service accounts using key-pair authentication"
  client_types = ["DRIVERS", "SNOWFLAKE_CLI", "SNOWSQL"]
}

import {
  to = snowflake_password_policy.admin_password_policy
  id = "ADMIN_PASSWORD_POLICY"
}

resource "snowflake_password_policy" "admin_password_policy" {
  name                          = "ADMIN_PASSWORD_POLICY"
  comment                       = "Enhanced password security for admin users"
  password_history              = 15
  password_lockout_time_mins    = 60
  password_max_age_days         = 60
  password_max_length           = 256
  password_max_retries          = 3
  password_min_length           = 16
  password_min_lower_case_chars = 2
  password_min_numeric_chars    = 2
  password_min_special_chars    = 2
  password_min_upper_case_chars = 2
}

import {
  to = snowflake_password_policy.service_password_policy
  id = "SERVICE_PASSWORD_POLICY"
}

resource "snowflake_password_policy" "service_password_policy" {
  name                          = "SERVICE_PASSWORD_POLICY"
  comment                       = "Temporary password policy for service accounts (migrate to RSA keys)"
  password_history              = 20
  password_lockout_time_mins    = 120
  password_max_age_days         = 180
  password_max_length           = 256
  password_max_retries          = 3
  password_min_length           = 20
  password_min_lower_case_chars = 2
  password_min_numeric_chars    = 3
  password_min_special_chars    = 2
  password_min_upper_case_chars = 2
}

import {
  to = snowflake_password_policy.standard_password_policy
  id = "STANDARD_PASSWORD_POLICY"
}

resource "snowflake_password_policy" "standard_password_policy" {
  name                          = "STANDARD_PASSWORD_POLICY"
  comment                       = "Standard password security for regular users"
  password_history              = 12
  password_lockout_time_mins    = 30
  password_max_age_days         = 90
  password_max_length           = 256
  password_max_retries          = 5
  password_min_length           = 14
  password_min_lower_case_chars = 1
  password_min_numeric_chars    = 2
  password_min_special_chars    = 1
  password_min_upper_case_chars = 1
}

import {
  to = snowflake_session_policy.admin_session_policy
  id = "ADMIN_SESSION_POLICY"
}

resource "snowflake_session_policy" "admin_session_policy" {
  name                         = "ADMIN_SESSION_POLICY"
  comment                      = "Strict session policy for admin users"
  session_idle_timeout_mins    = 15
  session_ui_idle_timeout_mins = 15
}

import {
  to = snowflake_session_policy.analyst_session_policy
  id = "ANALYST_SESSION_POLICY"
}

resource "snowflake_session_policy" "analyst_session_policy" {
  name                         = "ANALYST_SESSION_POLICY"
  comment                      = "Extended session policy for data analysts running long queries"
  session_idle_timeout_mins    = 180
  session_ui_idle_timeout_mins = 240
}

import {
  to = snowflake_session_policy.dev_session_policy
  id = "DEV_SESSION_POLICY"
}

resource "snowflake_session_policy" "dev_session_policy" {
  name                         = "DEV_SESSION_POLICY"
  comment                      = "Development environment session policy"
  session_idle_timeout_mins    = 120
  session_ui_idle_timeout_mins = 180
}

import {
  to = snowflake_session_policy.service_session_policy
  id = "SERVICE_SESSION_POLICY"
}

resource "snowflake_session_policy" "service_session_policy" {
  name                         = "SERVICE_SESSION_POLICY"
  comment                      = "Session policy for service accounts and automation"
  session_idle_timeout_mins    = 240
  session_ui_idle_timeout_mins = 60
}

import {
  to = snowflake_session_policy.user_session_policy
  id = "USER_SESSION_POLICY"
}

resource "snowflake_session_policy" "user_session_policy" {
  name                         = "USER_SESSION_POLICY"
  comment                      = "Standard session policy for regular users"
  session_idle_timeout_mins    = 60
  session_ui_idle_timeout_mins = 120
}
