# Generated by SnowTower - DO NOT EDIT MANUALLY
# Source: snowddl/ YAML configurations

# Resource monitor resources

import {
  to = snowflake_resource_monitor.analyst_warehouse_monitor
  id = "ANALYST_WAREHOUSE_MONITOR"
}

resource "snowflake_resource_monitor" "analyst_warehouse_monitor" {
  name             = "ANALYST_WAREHOUSE_MONITOR"
  credit_quota     = 100
  frequency        = "MONTHLY"
  notify_triggers  = [75, 90]
  suspend_triggers = [100]
}

import {
  to = snowflake_resource_monitor.dev_environment_monitor
  id = "DEV_ENVIRONMENT_MONITOR"
}

resource "snowflake_resource_monitor" "dev_environment_monitor" {
  name             = "DEV_ENVIRONMENT_MONITOR"
  credit_quota     = 500
  frequency        = "MONTHLY"
  notify_triggers  = [60, 80]
  suspend_triggers = [95]
}

import {
  to = snowflake_resource_monitor.dlt_pipeline_monitor
  id = "DLT_PIPELINE_MONITOR"
}

resource "snowflake_resource_monitor" "dlt_pipeline_monitor" {
  name             = "DLT_PIPELINE_MONITOR"
  credit_quota     = 300
  frequency        = "MONTHLY"
  notify_triggers  = [80, 95]
  suspend_triggers = [100]
}

import {
  to = snowflake_resource_monitor.emergency_cost_control
  id = "EMERGENCY_COST_CONTROL"
}

resource "snowflake_resource_monitor" "emergency_cost_control" {
  name             = "EMERGENCY_COST_CONTROL"
  credit_quota     = 1500
  frequency        = "MONTHLY"
  notify_triggers  = [95]
  suspend_triggers = [100]
}

import {
  to = snowflake_resource_monitor.pipeline_monitor
  id = "PIPELINE_MONITOR"
}

resource "snowflake_resource_monitor" "pipeline_monitor" {
  name             = "PIPELINE_MONITOR"
  credit_quota     = 500
  frequency        = "MONTHLY"
  notify_triggers  = [70, 85]
  suspend_triggers = [98]
}

import {
  to = snowflake_resource_monitor.snowtower_account_monitor
  id = "SNOWTOWER_ACCOUNT_MONITOR"
}

resource "snowflake_resource_monitor" "snowtower_account_monitor" {
  name             = "SNOWTOWER_ACCOUNT_MONITOR"
  credit_quota     = 1000
  frequency        = "MONTHLY"
  notify_triggers  = [50, 75, 90]
  suspend_triggers = [100]
}

import {
  to = snowflake_resource_monitor.snowtower_monitor
  id = "SNOWTOWER_MONITOR"
}

resource "snowflake_resource_monitor" "snowtower_monitor" {
  name             = "SNOWTOWER_MONITOR"
  credit_quota     = 50
  frequency        = "MONTHLY"
  notify_triggers  = [75, 90]
  suspend_triggers = [100]
}

import {
  to = snowflake_resource_monitor.weekly_spending_monitor
  id = "WEEKLY_SPENDING_MONITOR"
}

resource "snowflake_resource_monitor" "weekly_spending_monitor" {
  name            = "WEEKLY_SPENDING_MONITOR"
  credit_quota    = 150
  frequency       = "WEEKLY"
  notify_triggers = [80]
}
