# Generated by SnowTower - DO NOT EDIT MANUALLY
# Source: snowddl/ YAML configurations

# Role resources (business + tech)

import {
  to = snowflake_account_role.admin_role_b_role
  id = "ADMIN_ROLE__B_ROLE"
}

resource "snowflake_account_role" "admin_role_b_role" {
  name    = "ADMIN_ROLE__B_ROLE"
  comment = "Administrative business role with full access"
}

import {
  to = snowflake_account_role.ai_ml_role_b_role
  id = "AI_ML_ROLE__B_ROLE"
}

resource "snowflake_account_role" "ai_ml_role_b_role" {
  name    = "AI_ML_ROLE__B_ROLE"
  comment = "Business role for AI and ML workloads"
}

import {
  to = snowflake_account_role.bi_developer_role_b_role
  id = "BI_DEVELOPER_ROLE__B_ROLE"
}

resource "snowflake_account_role" "bi_developer_role_b_role" {
  name    = "BI_DEVELOPER_ROLE__B_ROLE"
  comment = "Business role for BI developers who create models and dashboards in ANALYTICS_TOOL using dbt transformations"
}

import {
  to = snowflake_account_role.company_users_b_role
  id = "COMPANY_USERS__B_ROLE"
}

resource "snowflake_account_role" "company_users_b_role" {
  name    = "COMPANY_USERS__B_ROLE"
  comment = "Business role for SnowTower team members doing data work"
}

import {
  to = snowflake_account_role.data_integration_role_b_role
  id = "DATA_INTEGRATION_ROLE__B_ROLE"
}

resource "snowflake_account_role" "data_integration_role_b_role" {
  name    = "DATA_INTEGRATION_ROLE__B_ROLE"
  comment = "Business role for data integration services"
}

import {
  to = snowflake_account_role.dbt_analytics_role_b_role
  id = "DBT_ANALYTICS_ROLE__B_ROLE"
}

resource "snowflake_account_role" "dbt_analytics_role_b_role" {
  name    = "DBT_ANALYTICS_ROLE__B_ROLE"
  comment = "Business role for dbt and analytics work - includes schema owner access for PROJ_STRIPE to modify existing tables/views"
}

import {
  to = snowflake_account_role.dlt_stripe_role_b_role
  id = "DLT_STRIPE_ROLE__B_ROLE"
}

resource "snowflake_account_role" "dlt_stripe_role_b_role" {
  name    = "DLT_STRIPE_ROLE__B_ROLE"
  comment = "Dedicated business role for DLT Stripe data pipeline - includes schema owner access for table stage operations"
}

import {
  to = snowflake_account_role.infrastructure_automation_role_b_role
  id = "INFRASTRUCTURE_AUTOMATION_ROLE__B_ROLE"
}

resource "snowflake_account_role" "infrastructure_automation_role_b_role" {
  name    = "INFRASTRUCTURE_AUTOMATION_ROLE__B_ROLE"
  comment = "Business role for infrastructure automation and deployment services"
}

import {
  to = snowflake_account_role.lightdash_business_role_b_role
  id = "LIGHTDASH_BUSINESS_ROLE__B_ROLE"
}

resource "snowflake_account_role" "lightdash_business_role_b_role" {
  name    = "LIGHTDASH_BUSINESS_ROLE__B_ROLE"
  comment = "Business role for LightDash BI platform - analytics and dashboard access with read/write to BI_TOOL database"
}

import {
  to = snowflake_account_role.omni_business_role_b_role
  id = "OMNI_BUSINESS_ROLE__B_ROLE"
}

resource "snowflake_account_role" "omni_business_role_b_role" {
  name    = "OMNI_BUSINESS_ROLE__B_ROLE"
  comment = "Business role for Omni BI platform - analytics and reporting access"
}

import {
  to = snowflake_account_role.recce_business_role_b_role
  id = "RECCE_BUSINESS_ROLE__B_ROLE"
}

resource "snowflake_account_role" "recce_business_role_b_role" {
  name    = "RECCE_BUSINESS_ROLE__B_ROLE"
  comment = "Business role for Recce dbt validation and data quality testing"
}

import {
  to = snowflake_account_role.service_accounts_role_b_role
  id = "SERVICE_ACCOUNTS_ROLE__B_ROLE"
}

resource "snowflake_account_role" "service_accounts_role_b_role" {
  name    = "SERVICE_ACCOUNTS_ROLE__B_ROLE"
  comment = "Business role for service accounts and integrations"
}

import {
  to = snowflake_account_role.streamlit_apps_role_b_role
  id = "STREAMLIT_APPS_ROLE__B_ROLE"
}

resource "snowflake_account_role" "streamlit_apps_role_b_role" {
  name    = "STREAMLIT_APPS_ROLE__B_ROLE"
  comment = "Business role for Streamlit applications and services"
}

import {
  to = snowflake_account_role.training_role_b_role
  id = "TRAINING_ROLE__B_ROLE"
}

resource "snowflake_account_role" "training_role_b_role" {
  name    = "TRAINING_ROLE__B_ROLE"
  comment = "Business role for training and development users"
}

import {
  to = snowflake_account_role.bi_writer_tech_role_t_role
  id = "BI_WRITER_TECH_ROLE__T_ROLE"
}

resource "snowflake_account_role" "bi_writer_tech_role_t_role" {
  name    = "BI_WRITER_TECH_ROLE__T_ROLE"
  comment = "Technical role for BI developers who need to read from transformed data and write to ANALYTICS_TOOL"
}

import {
  to = snowflake_account_role.company_users_t_role
  id = "COMPANY_USERS__T_ROLE"
}

resource "snowflake_account_role" "company_users_t_role" {
  name    = "COMPANY_USERS__T_ROLE"
  comment = "SnowTower team members role with development database access"
}

import {
  to = snowflake_account_role.copilot_access_role_t_role
  id = "COPILOT_ACCESS_ROLE__T_ROLE"
}

resource "snowflake_account_role" "copilot_access_role_t_role" {
  name    = "COPILOT_ACCESS_ROLE__T_ROLE"
  comment = "Role for Copilot access and AI integrations"
}

import {
  to = snowflake_account_role.dbt_stripe_role_t_role
  id = "DBT_STRIPE_ROLE__T_ROLE"
}

resource "snowflake_account_role" "dbt_stripe_role_t_role" {
  name    = "DBT_STRIPE_ROLE__T_ROLE"
  comment = "dbt service role for Stripe transformations - Read-only access to SOURCE_STRIPE (DLT-owned source data), full read/write access to PROJ_STRIPE and ANALYTICS_TOOL for transformed models and analytics"
}

import {
  to = snowflake_account_role.dbt_training_t_role
  id = "DBT_TRAINING__T_ROLE"
}

resource "snowflake_account_role" "dbt_training_t_role" {
  name    = "DBT_TRAINING__T_ROLE"
  comment = "Training role for dbt users and courses"
}

import {
  to = snowflake_account_role.dlt_loader_role_t_role
  id = "DLT_LOADER_ROLE__T_ROLE"
}

resource "snowflake_account_role" "dlt_loader_role_t_role" {
  name    = "DLT_LOADER_ROLE__T_ROLE"
  comment = "Data loading role for DLT operations with SOURCE_STRIPE permissions"
}

import {
  to = snowflake_account_role.dlt_stripe_tech_role_t_role
  id = "DLT_STRIPE_TECH_ROLE__T_ROLE"
}

resource "snowflake_account_role" "dlt_stripe_tech_role_t_role" {
  name    = "DLT_STRIPE_TECH_ROLE__T_ROLE"
  comment = "Dedicated technical role for DLT Stripe pipeline - comprehensive permissions for data loading operations including table stage access via schema owner role."
}

import {
  to = snowflake_account_role.estuary_t_role
  id = "ESTUARY__T_ROLE"
}

resource "snowflake_account_role" "estuary_t_role" {
  name    = "ESTUARY__T_ROLE"
  comment = "Estuary data integration service role"
}

import {
  to = snowflake_account_role.fabi_ai_t_role
  id = "FABI_AI__T_ROLE"
}

resource "snowflake_account_role" "fabi_ai_t_role" {
  name    = "FABI_AI__T_ROLE"
  comment = "Fabi AI service role for AI/ML operations"
}

import {
  to = snowflake_account_role.fivetran_t_role
  id = "FIVETRAN__T_ROLE"
}

resource "snowflake_account_role" "fivetran_t_role" {
  name    = "FIVETRAN__T_ROLE"
  comment = "Fivetran data integration service role"
}

import {
  to = snowflake_account_role.fivetran_role_t_role
  id = "FIVETRAN_ROLE__T_ROLE"
}

resource "snowflake_account_role" "fivetran_role_t_role" {
  name    = "FIVETRAN_ROLE__T_ROLE"
  comment = "Alternative Fivetran role for data integration operations"
}

import {
  to = snowflake_account_role.lightdash_tech_role_t_role
  id = "LIGHTDASH_TECH_ROLE__T_ROLE"
}

resource "snowflake_account_role" "lightdash_tech_role_t_role" {
  name    = "LIGHTDASH_TECH_ROLE__T_ROLE"
  comment = "LightDash BI platform technical role - Read access to source data, full read/write access to BI_TOOL database for dashboard content and analytics"
}

import {
  to = snowflake_account_role.matillion_role_t_role
  id = "MATILLION_ROLE__T_ROLE"
}

resource "snowflake_account_role" "matillion_role_t_role" {
  name    = "MATILLION_ROLE__T_ROLE"
  comment = "Matillion ETL processing service role"
}

import {
  to = snowflake_account_role.omni_infrastructure_automation_t_role
  id = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
}

resource "snowflake_account_role" "omni_infrastructure_automation_t_role" {
  name    = "OMNI_INFRASTRUCTURE_AUTOMATION__T_ROLE"
  comment = "Omni infrastructure automation role for automated deployment and management"
}

import {
  to = snowflake_account_role.omni_tech_role_t_role
  id = "OMNI_TECH_ROLE__T_ROLE"
}

resource "snowflake_account_role" "omni_tech_role_t_role" {
  name    = "OMNI_TECH_ROLE__T_ROLE"
  comment = "Omni BI platform technical role - Read access to PROJ_STRIPE, full write access to ANALYTICS_TOOL database"
}

import {
  to = snowflake_account_role.recce_tech_role_t_role
  id = "RECCE_TECH_ROLE__T_ROLE"
}

resource "snowflake_account_role" "recce_tech_role_t_role" {
  name    = "RECCE_TECH_ROLE__T_ROLE"
  comment = "Technical role for Recce dbt validation - Read-only access to PROJ_STRIPE for model validation and data quality testing"
}

import {
  to = snowflake_account_role.sigma_role_t_role
  id = "SIGMA_ROLE__T_ROLE"
}

resource "snowflake_account_role" "sigma_role_t_role" {
  name    = "SIGMA_ROLE__T_ROLE"
  comment = "Sigma BI analytics service role"
}

import {
  to = snowflake_account_role.snowtower_users_t_role
  id = "SNOWTOWER_USERS__T_ROLE"
}

resource "snowflake_account_role" "snowtower_users_t_role" {
  name    = "SNOWTOWER_USERS__T_ROLE"
  comment = "SnowTower application users role"
}

import {
  to = snowflake_account_role.streamlit_role_t_role
  id = "STREAMLIT_ROLE__T_ROLE"
}

resource "snowflake_account_role" "streamlit_role_t_role" {
  name    = "STREAMLIT_ROLE__T_ROLE"
  comment = "Streamlit applications service role"
}

import {
  to = snowflake_account_role.streamlit_towerapp_role_t_role
  id = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
}

resource "snowflake_account_role" "streamlit_towerapp_role_t_role" {
  name    = "STREAMLIT_TOWERAPP_ROLE__T_ROLE"
  comment = "SnowTower Streamlit application specific role"
}

import {
  to = snowflake_account_role.streamlit_viewer_t_role
  id = "STREAMLIT_VIEWER__T_ROLE"
}

resource "snowflake_account_role" "streamlit_viewer_t_role" {
  name    = "STREAMLIT_VIEWER__T_ROLE"
  comment = "Read-only infrastructure viewer role for Streamlit app users - provides minimal metadata access without data privileges"
}

import {
  to = snowflake_account_role.stripe_t_role
  id = "STRIPE__T_ROLE"
}

resource "snowflake_account_role" "stripe_t_role" {
  name    = "STRIPE__T_ROLE"
  comment = "Stripe data access role with read permissions to SOURCE_STRIPE and write permissions to PROJ_STRIPE"
}

import {
  to = snowflake_account_role.tobiko_cloud_t_role
  id = "TOBIKO_CLOUD__T_ROLE"
}

resource "snowflake_account_role" "tobiko_cloud_t_role" {
  name    = "TOBIKO_CLOUD__T_ROLE"
  comment = "Tobiko Cloud service role"
}
