# Generated by SnowTower - DO NOT EDIT MANUALLY
# Source: snowddl/ YAML configurations

# User resources

import {
  to = snowflake_user.alice_admin
  id = "ALICE_ADMIN"
}

resource "snowflake_user" "alice_admin" {
  name         = "ALICE_ADMIN"
  email        = "alice.admin@example.com"
  first_name   = "Alice"
  last_name    = "Admin"
  default_role = "SYSADMIN"
  comment      = "Platform administrator"
  user_type    = "PERSON"
}

import {
  to = snowflake_user.dbt_service
  id = "DBT_SERVICE"
}

resource "snowflake_user" "dbt_service" {
  name           = "DBT_SERVICE"
  default_role   = "DBT_ANALYTICS_ROLE__B_ROLE"
  comment        = "dbt transformation service account"
  user_type      = "SERVICE"
  rsa_public_key = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0example...
...replace with your actual RSA public key...
AQAB"
}

import {
  to = snowflake_user.dlt_service
  id = "DLT_SERVICE"
}

resource "snowflake_user" "dlt_service" {
  name           = "DLT_SERVICE"
  default_role   = "DLT_STRIPE_ROLE__B_ROLE"
  comment        = "Data ingestion service account"
  user_type      = "SERVICE"
  rsa_public_key = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0example...
...replace with your actual RSA public key...
AQAB"
}

import {
  to = snowflake_user.john_analyst
  id = "JOHN_ANALYST"
}

resource "snowflake_user" "john_analyst" {
  name         = "JOHN_ANALYST"
  email        = "john.analyst@example.com"
  first_name   = "John"
  last_name    = "Analyst"
  default_role = "COMPANY_USERS__B_ROLE"
  comment      = "Data analyst"
  user_type    = "PERSON"
}
