# Generated by SnowTower - DO NOT EDIT MANUALLY
# Source: snowddl/ YAML configurations

# Warehouse resources

import {
  to = snowflake_warehouse.admin
  id = "ADMIN"
}

resource "snowflake_warehouse" "admin" {
  name           = "ADMIN"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Administrative warehouse for admin operations"
}

import {
  to = snowflake_warehouse.analyst_wh
  id = "ANALYST_WH"
}

resource "snowflake_warehouse" "analyst_wh" {
  name             = "ANALYST_WH"
  warehouse_size   = "XSMALL"
  auto_suspend     = 60
  auto_resume      = true
  comment          = "Warehouse for analyst workloads"
  resource_monitor = "ANALYST_WAREHOUSE_MONITOR"
}

import {
  to = snowflake_warehouse.analytics_tool
  id = "ANALYTICS_TOOL"
}

resource "snowflake_warehouse" "analytics_tool" {
  name           = "ANALYTICS_TOOL"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Omni BI platform warehouse for analytics and reporting queries"
}

import {
  to = snowflake_warehouse.bi_tool
  id = "BI_TOOL"
}

resource "snowflake_warehouse" "bi_tool" {
  name           = "BI_TOOL"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "LightDash BI platform warehouse for analytics and dashboard queries"
}

import {
  to = snowflake_warehouse.dbt_stripe_wh
  id = "DBT_STRIPE_WH"
}

resource "snowflake_warehouse" "dbt_stripe_wh" {
  name           = "DBT_STRIPE_WH"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "dbt Stripe transformation operations"
}

import {
  to = snowflake_warehouse.dev_frank_wh
  id = "DEV_FRANK_WH"
}

resource "snowflake_warehouse" "dev_frank_wh" {
  name           = "DEV_FRANK_WH"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Polo's dedicated development warehouse for data engineering work"
}

import {
  to = snowflake_warehouse.dev_wh
  id = "DEV_WH"
}

resource "snowflake_warehouse" "dev_wh" {
  name           = "DEV_WH"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Development warehouse for personal dev environments"
}

import {
  to = snowflake_warehouse.dlt
  id = "DLT"
}

resource "snowflake_warehouse" "dlt" {
  name             = "DLT"
  warehouse_size   = "XSMALL"
  auto_suspend     = 60
  auto_resume      = true
  comment          = "DLT data loading and pipeline operations"
  resource_monitor = "DLT_PIPELINE_MONITOR"
}

import {
  to = snowflake_warehouse.estuary
  id = "ESTUARY"
}

resource "snowflake_warehouse" "estuary" {
  name           = "ESTUARY"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Estuary data integration warehouse"
}

import {
  to = snowflake_warehouse.fabi_ai_warehouse
  id = "FABI_AI_WAREHOUSE"
}

resource "snowflake_warehouse" "fabi_ai_warehouse" {
  name           = "FABI_AI_WAREHOUSE"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Fabi AI workloads and model training"
}

import {
  to = snowflake_warehouse.fivetran
  id = "FIVETRAN"
}

resource "snowflake_warehouse" "fivetran" {
  name           = "FIVETRAN"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Fivetran data integration warehouse"
}

import {
  to = snowflake_warehouse.main_warehouse
  id = "MAIN_WAREHOUSE"
}

resource "snowflake_warehouse" "main_warehouse" {
  name             = "MAIN_WAREHOUSE"
  warehouse_size   = "XSMALL"
  auto_suspend     = 60
  auto_resume      = true
  comment          = "SnowTower team warehouse for data work and analytics"
  resource_monitor = "DEV_ENVIRONMENT_MONITOR"
}

import {
  to = snowflake_warehouse.recce
  id = "RECCE"
}

resource "snowflake_warehouse" "recce" {
  name           = "RECCE"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Recce dbt validation and data quality testing warehouse"
}

import {
  to = snowflake_warehouse.streamlit_viewer_wh
  id = "STREAMLIT_VIEWER_WH"
}

resource "snowflake_warehouse" "streamlit_viewer_wh" {
  name              = "STREAMLIT_VIEWER_WH"
  warehouse_size    = "XSMALL"
  auto_suspend      = 60
  auto_resume       = true
  comment           = "Dedicated warehouse for Streamlit viewer metadata queries - minimal resources for cost efficiency"
  resource_monitor  = "SNOWTOWER_MONITOR"
  min_cluster_count = 1
  max_cluster_count = 1
}

import {
  to = snowflake_warehouse.stripe
  id = "STRIPE"
}

resource "snowflake_warehouse" "stripe" {
  name           = "STRIPE"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Stripe data processing and analytics"
}

import {
  to = snowflake_warehouse.transforming
  id = "TRANSFORMING"
}

resource "snowflake_warehouse" "transforming" {
  name           = "TRANSFORMING"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "General data transformation warehouse"
}

import {
  to = snowflake_warehouse.transforming_user
  id = "TRANSFORMING_USER"
}

resource "snowflake_warehouse" "transforming_user" {
  name           = "TRANSFORMING_USER"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "Heather's training transformation warehouse"
}
